### ISSUE TITLE
Is there a way to use this extension without building a mix project?

### ISSUE THREAD

**Issue by abishekaditya** [fr1zle/vscode-elixir#101]
I am using exercism and my elixir folder contains pre-written pieces of tests and code in folders that do not have any mix files attached to them. I am not able to use the features of your extension in these situations.
Is this a bug on my end? Or is this not supported?

**Comment by fr1zle** [comment]
Hi,

currently we can only support Mix projects.

**Comment by abishekaditya** [comment]
Ok, Thanks
