### ISSUE TITLE
Proposal: Add configuration property for "elixir" command

### ISSUE THREAD

**Issue by vheathen** [fr1zle/vscode-elixir#109]
Hello!

I'm running VS Code on Windows, but have my elixir dev environment inside of the WSL (Windows Subsystem for Linux). I struggled to get vscode-elixir work but it didn't (for the obvious reasons). 

Finally I've found a temporary solution until vscode itself be able to work with\run extensions inside WSL natively. But for this I need a custom command to run elixir processes. Now it is possible only by dirty editing of `elixirSenseServerProcess.js` and `elixirServer.js`. 

So to keep upgradability is it possible to introduce a configuration property to choose the correct\needed elixir command path?

P.S. For any interested in how to force win vscode-elixir work with WSL:
1. Take `wsl-bash-run.bat` and `wsl-bash-run.ps1` from [this repo](https://github.com/giovdk21/wsl-bash-tools) (thanks a lot to @giovdk21).
2. Create in the same folder an intermediate `wsl-bash-elixir.bat` file with the following code:
```
@echo off
%~dp0wsl-bash-run.bat elixir %*
```
or just change `args=""` to `args="elixir "` (don't forget trailing space after `elixir`) in the `wsl-bash-run.ps1`.
3. Edit `elixirSenseServerProcess.js` and `elixirServer.js` changing `this.command = 'elixir';` to `this.command='C://path//to//wsl-bash-elixir.bat';`
4. To have "Go to to definition" feature works create fake `/mnt/c` link on the drive you use in Windows. Open cmd.exe as administrator and type:
```
mkdir c:\mnt
mklink /d c:\mnt\c c:\
```
You may need to change C: to your drive letter.
5. You will optionally need to edit `wsl-bash-run.ps1` and change `bash -c` to `bash -lc` because bash -c runs as a non-interactive shell, so it won't read .bashrc\.profile and therefore doesn't populate env variables\aliases (and I was needed this as I'm using asdf package manager).
6. Restart VS Code, open debug console and you might see something like this:
```
[Extension Host] [ElixirSense] warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  /mnt/c/Users/vlad/.vscode/extensions/mjmcloug.vscode-elixir-1.1.0/elixir_sense/lib/elixir_sense/core/source.ex:97

[Extension Host] [ElixirSense] warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  /mnt/c/Users/vlad/.vscode/extensions/mjmcloug.vscode-elixir-1.1.0/elixir_sense/lib/alchemist/helpers/complete.ex:21

[Extension Host] [ElixirSense] warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  /mnt/c/Users/vlad/.vscode/extensions/mjmcloug.vscode-elixir-1.1.0/elixir_sense/lib/alchemist/helpers/complete.ex:134

[Extension Host] [ElixirSense] warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  /mnt/c/Users/vlad/.vscode/extensions/mjmcloug.vscode-elixir-1.1.0/elixir_sense/lib/elixir_sense/server/tcp_server.ex:124

[Extension Host] [ElixirSense] warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  /mnt/c/Users/vlad/.vscode/extensions/mjmcloug.vscode-elixir-1.1.0/elixir_sense/lib/elixir_sense/server/tcp_server.ex:125

[Extension Host] [ElixirSense] Initializing ElixirSense server for environment "dev" (Elixir version 1.5.2)

[Extension Host] [ElixirSense] Working directory is "/mnt/c/cloud/Documents/Projects/JustMoney/profile_umbrella/profile"

[Extension Host] ok:localhost:51913:y6V/Mz1Q7WAWuzAM8xIvIKdKQj9nYTjoTbvjPtTY3ToDemqQZXv0WozUKKUCMLEXgHvl7BYlhxVqTOKlTou8Eg==

[Extension Host] [vscode-elixir] ElixirSense client connected on localhost:51913
```

**Comment by fr1zle** [comment]
Yeah, wanted to support this for a long time now. Will try to get this done this weekend.

**Comment by fr1zle** [comment]
@vheathen : Would you mind testing https://github.com/fr1zle/vscode-elixir/pull/115 with your setup? The configuration is called `elixir.command`.

**Comment by vheathen** [comment]
@fr1zle sorry for a long reply! Sure, I'll test it on week-end!

**Comment by vheathen** [comment]
Thanks a lot for this feature, it seems to work!

**Comment by JPYamamoto** [comment]
Is it possible to use the elixir executable inside WSL without those extra files? If so, could you document it? Thanks
