### ISSUE TITLE
Emmet doesn't work in eex files.

### ISSUE THREAD

**Issue by Fahrradflucht** [fr1zle/vscode-elixir#11]
If you hit `tab` or fire the emmet expand abbr. command via the command it just makes a tab in eex files. I think it would be nice if it kept working like it does in HTML.

**Comment by fr1zle** [comment]
Noticed this as well, will look into it once i find some time

**Comment by Fahrradflucht** [comment]
Just to clarify whats going on (at least how I understand it):

The filetypes in which Emmet is enabled are [hardcoded in the vscode source](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/emmet/node/editorAccessor.ts#L20) at the moment. That means the only way we could get emmet to work in `.eex` files is to associate the `.eex` extension with html but that would be bad because we would loose the elixir capabilities.

This means we are blocked on the issue above with this. Good news is that it's on the milestone for august.

**Comment by Fahrradflucht** [comment]
I looked into this and tried to implement it like it is done in [vscode-vash](https://github.com/mrmlnc/vscode-vash) and described [here](https://github.com/Microsoft/vscode/issues/11139) but I couldn't yet get it to work.

@fr1zle could you explain to me why there are two files for eex syntax ([eex.json](https://github.com/mat-mcloughlin/vscode-elixir/blob/master/syntaxes/eex.json) and [html (eex).json](https://github.com/mat-mcloughlin/vscode-elixir/blob/master/syntaxes/html%20(eex).json))? I don't quite get the difference.

@mrmInc sorry for bothering you with this extension but you seem to have it working with vscode-vash. Can you tell at a glance why it isn't already working for `html (exx)`? I mean it [already has `text.html.elixir` as a scope name](https://github.com/mat-mcloughlin/vscode-elixir/blob/master/syntaxes/html%20(eex).json#L16)...

**Comment by mrmlnc** [comment]
@Fahrradflucht, 

In your case you have incorrect format identifiers. See:
 
  * https://github.com/mat-mcloughlin/vscode-elixir/blob/master/package.json#L22 - Correct
  * https://github.com/mat-mcloughlin/vscode-elixir/blob/master/package.json#L34 - Incorrect. Should be `eex`
  * https://github.com/mat-mcloughlin/vscode-elixir/blob/master/package.json#L44 - Incorrect. Should be `htmlexx`

Now you can use the following format:

```json
"emmet.syntaxProfiles": {
  "HTML (Eex)": "html"
}
```

**Comment by Pranz** [comment]
I have added
```
"emmet.syntaxProfiles": {
  "HTML (Eex)": "html"
}
```
to my config and reloaded, yet emmet still doesn't work on Eex files. My `html.eex` files have the language ID `HTML (Eex)` when opened.

**Comment by fr1zle** [comment]
Can reproduce.

Seems to be an issue with the new emmet (2.0): https://code.visualstudio.com/docs/editor/emmet
Will look into it.

**Comment by ashleyconnor** [comment]
@Pranz - try adding `"emmet.includeLanguages": {"HTML (Eex)": "html"}`

**Comment by fr1zle** [comment]
@ashleyconnor : This seems to work when a added to a user settings. Somehow this does not work if I add a contribution to the extension providing the setting...

Any ideas?

**Comment by Pranz** [comment]
@ashleyconnor Thanks, works if I put it in my user config.

**Comment by smahi** [comment]
@ashleyconnor thank you so much.

**Comment by koutselakismanos** [comment]
Now its "HTML (EEx)" not "HTML (Eex)"

**Comment by mplatts** [comment]
If you're using elixir-ls plugin - it's now:

```json
"html-eex": "html"
```

**Comment by lastobelus** [comment]
`"emmet.includeLanguages": { "html-eex": "html" }` is working for me for .eex & .leex files, but has anyone figured out how to get emmet expansion in sigils?

```
  def render(assigns) do
    ~L"""
      emmet here???
    """
```

**Comment by sbaildon** [comment]
> `"emmet.includeLanguages": { "html-eex": "html" }` is working for me for .eex & .leex files, but has anyone figured out how to get emmet expansion in sigils?
> 
> ```
>   def render(assigns) do
>     ~L"""
>       emmet here???
>     """
> ```

Yes, you can do 

```
"emmet.includeLanguages": {
    "elixir": "html",
    "markdown": "md",
},
```

The key is the language type, and the value is an "emmet supported language", although what those values are is a bit ambiguous (see https://github.com/microsoft/vscode-docs/issues/3935)

**Comment by bottlenecked** [comment]
For anyone looking support for the new `.heex` the language you need to
- install the Phoenix Framework vs-code extension from https://marketplace.visualstudio.com/items?itemName=phoenixframework.phoenix
- add the following configuration
```js
    "emmet.includeLanguages": {
        ...
        "phoenix-heex": "html",
        ...
    }
```
