### ISSUE TITLE
Symbol provider not working

### ISSUE THREAD

**Issue by Coffei** [fr1zle/vscode-elixir#125]
Hi,
the symbol search in elixir files does not work for me, when I invoke "Go To Symbol In FIle" with Ctrl+Shift+O I only see `No symbol information for this file`.

As I would like to use it to quickly move between functions, as I do in spacemacs, I did a little search and found there is an implementation that should work - [vscode-elixir/src/elixirSymbolProvider.ts](https://github.com/fr1zle/vscode-elixir/blob/master/src/elixirSymbolProvider.ts). I even see it is registered in the main file [elixirMain.ts#L60](https://github.com/fr1zle/vscode-elixir/blob/master/src/elixirMain.ts#L60)

Why doesn't this work? Is it turned off on purpose or is that a bug?

**Comment by fr1zle** [comment]
I havent come around to release this version yet. Will try to do so this week.

**Comment by Coffei** [comment]
Ah, good. I think I tried running the extension from source and saw no difference, but that was some time ago. I'll try the same today and let you know.

**Comment by Coffei** [comment]
OK, on master it also doesn't work, although it behaves differently. On master it seems to be _processing_ the file, as it displays an indefinite progress bar below the search input - https://imgur.com/a/e6K3H.

**Comment by pbudzik** [comment]
@Coffei full support for this is in the PR: https://github.com/fr1zle/vscode-elixir/pull/117 ... waiting for merge :)

**Comment by Coffei** [comment]
OK, I got confused since the provider in master looks like it should do something but doesn't. Since we already have a PR for better implementation I guess we can close this issue.
Thank you!
