### ISSUE TITLE
Improvements for documentation

### ISSUE THREAD

**Issue by ssijak** [fr1zle/vscode-elixir#13]
Is there a way to incorporate DOCL command of alchemist server into vscode-elixir plugin. Is there a standard "trigger" that could trigger that command in vscode? Or it could be bind to a shortcut? DEFL is used for autocompletion and it is great, but sometimes I would need more help documentation provided by DOCL. Maybe I could implement it if you could just point me into the right direction (how to bind to a shortcut to trigger needed command).
Also a minor thing. When I use autocompletion for example Enum.chunk definition is shown until I write ( -> Enum.chunk(   It disappear then. Can it still be shown until function call is written, it is useful to see function params while writing it?

**Comment by ssijak** [comment]
I cloned the repo and when try to start the extension from the vscode and open mix project it fails with : 

    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)

**Comment by fr1zle** [comment]
This may be a new issue with Elixir 1.3
Will try to look into it this weekend

**Comment by fr1zle** [comment]
This has been implemented via #35
