### ISSUE TITLE
Keep an eye on alchemist-server/ElixirSense

### ISSUE THREAD

**Issue by Fahrradflucht** [fr1zle/vscode-elixir#28]
I'm just opening this issue because the @mat-mcloughlin mention didn't work. @msaraiva plans to do a refactoring/rewrite of the alchemist-server and I think we should really keep an eye out for this.

Read more [here](https://github.com/tonini/alchemist-server/issues/6#issuecomment-256243983)

**Comment by fr1zle** [comment]
Tracked in #60
