### ISSUE TITLE
word based suggestions not work

### ISSUE THREAD

**Issue by wildchildEric** [fr1zle/vscode-elixir#30]
seems that it breaks the word based suggestions supported by default.

**Comment by mat-mcloughlin** [comment]
I'm not sure what you mean by word based suggestions, Is there any chance you could you please clarify

**Comment by eduardonunesp** [comment]
@mat-mcloughlin I think @wildchildEric is talking about the words which appear in the autocomplete  box, the words related to the current file

**Comment by mat-mcloughlin** [comment]
ah the default auto completion functionality. Would this still be useful? I kinda think it might make it more difficult to find the completion you require

Thoughts?

**Comment by eduardonunesp** [comment]
Kind of useful though, it's good to have some words next to the fingers, actually I think the priority is the Elixir completion then the suggestion it's ok to have too

**Comment by matramos** [comment]
I also have this **bug**.
It doesn't suggest anything. Nor elixir related, or variables in the program related.

**Comment by jakedeichert** [comment]
I had the same issue yesterday @matramos. My intellisense is now working after installing elixir with homebrew on macOS. Not sure about Windows.

It wasn't working for me because I do local development inside docker containers and native programs like vscode can't find/run/reference software in my container (such as elixir). Although, I can still develop in my container and just let vscode-elixir use the system installed version.. nothing wrong with that.

**Comment by fr1zle** [comment]
Currently we don't queue reguests to the alchemist-server: https://github.com/mat-mcloughlin/vscode-elixir/blob/master/src/elixirServer.ts#L98

This may result in Completion sometimes not appearing. That should however not lead to word based suggestion not working. I havent been able to reproduce this yet.

**Comment by hbobenicio** [comment]
Same issue here.

**Comment by mrkaspa** [comment]
is there a way to solve this?

**Comment by fr1zle** [comment]
Sadly no, this is an issue with vscode. You can read up on it in #56

Although I must say that i rarely find the word based suggestion that useful anyway. At least when the elixir sense autocomplete is working properly (which it should, if you regulary recompile your project.)

**Comment by fr1zle** [comment]
see #56 & Microsoft/vscode#21611
