### ISSUE TITLE
Symbol Marking

### ISSUE THREAD

**Issue by kexoth** [fr1zle/vscode-elixir#38]
This extension doesn't support symbol navigation as I tested on my projects, i.e. when you type `cmd+shift+O` it says `No symbol information for this file.`

Does this extension support this, if not are there any plans to support it in near future?

Thanks for the awesome work on this extension so far 👍

**Comment by the-shank** [comment]
This would be really useful !

**Comment by kexoth** [comment]
For anyone interested on the matter, there's a [separate plugin which includes symbols](http://github.com/perix4/vs-code-elixir-symbols) & works as expected.

**Comment by the-shank** [comment]
@kexoth Thanks, will check it out
