### ISSUE TITLE
Autocomplete doesn't trigger when there's already a suggestion popup.

### ISSUE THREAD

**Issue by Chillee** [fr1zle/vscode-elixir#41]
For example, as I type List, an autocomplete box pops up suggesting the list module. However, at the end, when I press ".", which should trigger autocomplete, all it does is remove the current autocomplete box. I need to then delete the period and retype it to trigger autocomplete.

1. Start typing List.zip
2. Autocomplete shows up while typing List, but disappears once you type the period.
3. You need to retype the period to trigger autocomplete.

This behavior does not occur in C++ or Python autocomplete, and occurs after disabling all other relevant modules.

**Comment by fr1zle** [comment]
Can reproduce, thanks for reporting
