### ISSUE TITLE
User snippets aren't working in eex/HTML (Eex)

### ISSUE THREAD

**Issue by lebart** [fr1zle/vscode-elixir#42]
Hello, 

I'm trying adding some snippets for my eex files but they wouldn't show up. At first I was thinking that my installation/settings could be in conflict. But after a clean install I cannot make them working. 

Infos: 

Mac os: 10.12.2
VSCode: 1.8.1
VSCode-Elixir: 0.1.1

In a phoenix project, I go to : 

code > pref > user snippets

I select HTML (Eex) and add this for instance: 

```
{
  "<%= %>": {
    "prefix": "=",
    "body": ["<%= $1 %>"],
    "description": "<%= %> with ="
  },
  "eex end tag": {
     "prefix": "end",
     "body": ["<% end %>$1"],
     "description": "eex end tag"
  }
}
```

I try to add those in snippets for eex files without success. 

Snippets for other languages are working. 

Any idea why this is happening?

**Comment by lebart** [comment]
I try to add them directly in the extension folder:
 
Inside package.json: 

```
		"snippets": [
			{
				"language": "elixir",
				"path": "./snippets/snippets.json"
			},
			{
				"language": "HTML (Eex)",
				"path": "./snippets/html.eex.json"
			}
		]
```

Putting snippets inside `snippets/html.eex.json` file make them work (after a vscode restart), but user snippets (not via the extension) are still not working. 

I read the "how to make an extension" docs, but I didn't find out how to "enable" the user snippet for a specific language. 

In the extension description/contribution tab the HTML (Eex) snippets support seems "off" even after my monkey patch. 

Is there a way different way to enable it other than what I did in the package.json file ?

**Comment by lperiodbose** [comment]
I followed @lebart 's steps above modifying the package by hand and was finally able to add snippets. My install is able to add user snippets for .ex and .eex, but not for the .html.eex language. It's really odd.

**Comment by lebart** [comment]
@lperiodbose I end up making my own extension for the snippets. I'll post the steps I've done for the html.eex files or if I have more time I'll publish the extension for the snippets.

**Comment by fr1zle** [comment]
Sorry to hear you guys are having issues. It might be due to HTML (Eex) having some specials chars in its name.

I will look into other extensions to see how they do their naming.

**Comment by lebart** [comment]
@fr1zle that would be great, I think it's better allowing user snippets and keep a unique extension for elixir.

**Comment by fr1zle** [comment]
@lebart & @lperiodbose this seems to work now with the latest code & extension version. 

Are you still having issues?

**Comment by fr1zle** [comment]
Closing this as there was no more feedback.

**Comment by abartier** [comment]
@fr1zle sorry I missed your last update. I'll reopen it if not resolved. 
Thanks !
