### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by assafmo** [fr1zle/vscode-elixir#51]
Please add support for code formatting (like https://golang.org/cmd/gofmt/ fo go).

**Comment by Fahrradflucht** [comment]
How do you imagine this feature? There is no standard tool in elixir for code formatting like there is `gofmt` in go.

There [was a discussion](https://groups.google.com/forum/#!topic/elixir-lang-talk/CfYVmQpKPIw) on the elixir-lang-talk mailing list about this and the feature request was basically dismissed.

That said I thought about a similar feature today: There are basically two big linters in the elixir world, [Dogma](https://github.com/lpil/dogma) and [credo](https://github.com/rrrene/credo). I think it would be great to have integration for one of them in vscode. But neither credo nor dogma support automatic fixing of the queried code.

**Comment by assafmo** [comment]
The basic is probably just provide indentation when the keymap for `editor.action.formatDocument` is hit.
E.g.
```elixir
        def handle_call({:lookup, name}, _from, {names, _} = state) do
{:reply, Map.fetch(names, name), state}
           end
```
Or
```elixir
        def handle_call({:lookup, name}, _from, {names, _} = state) do {:reply, Map.fetch(names, name), state}           end
```
Will become
```elixir
def handle_call({:lookup, name}, _from, {names, _} = state) do
    {:reply, Map.fetch(names, name), state}
end
```

**Comment by kexoth** [comment]
@assafmo the right place to ask for this feature is Microsoft/vscode#4039

**Comment by fr1zle** [comment]
@assafmo I don't think there is any tool for formatting that is widly accepted by the community.
I agree that this would be somewhat useful but it seems that the community has decided against it for now.

I also think code formatting is best done independent of the used editor, Therefor i will (for now) close this issue.

**Comment by agonzalezro** [comment]
Hi!

Could we reopen the discussion after Elixir 1.6 introduced  `format`?

There are some tools already that do it: https://marketplace.visualstudio.com/items?itemName=sammkj.vscode-elixir-formatter, do you want to keep them separate or do you think it's a good addition to `vscode-elixir`?

**Comment by fr1zle** [comment]
Hey @agonzalezro,
i opened #99  for this a few days ago. @securingsincity started working on this in #102
