### ISSUE TITLE
Different highlight for variables starting with underscore

### ISSUE THREAD

**Issue by dmzkrsk** [fr1zle/vscode-elixir#62]
Atom has it. Can it be implemented for VS Code?

**Comment by edevil** [comment]
Shouldn't atoms be highlighted as well?

**Comment by luizdamim** [comment]
I tried to tackle this issue and found that variables starting with underscore are identified as `unused.comment.elixir` scope, but I couldn't figure out where to set the color.

But VSCode's July update (1.15, released yesterday) added [custom syntax highlighting](https://code.visualstudio.com/updates/v1_15#_user-definable-syntax-highlighting-colors) where you can now customize the editor syntax highlighting colors in user settings.

Add this to your user settings and you should have underscore variables with the same color as comments.

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": "unused.comment.elixir",
      "settings": {
        "foreground": "#5C6370"
      }
    }
  ]
}
```

**Comment by mkaput** [comment]
@edevil These settings also include colours for atoms (I also slightly tuned unused var colour)

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": "unused.comment.elixir",
            "settings": {
                "foreground": "#78909c"
            }
        },
        {
            "scope": "wildcard.comment.elixir",
            "settings": {
                "foreground": "#78909c"
            }
        },
        {
            "scope": "punctuation.definition.constant.elixir",
            "settings": {
                "foreground": "#80cbc4"
            }
        },
        {
            "scope": "constant.other.symbol.elixir",
            "settings": {
                "foreground": "#80cbc4"
            }
        }
    ]
}
```

**Comment by alex88** [comment]
Nice! Will these be included in the next release?

**Comment by fr1zle** [comment]
If theres anything we can do in the extension, let me know. I do not have a lot of experience with configuring the syntaxes.

**Comment by pikeas** [comment]
Just switched from ST to VS Code, atom highlighting is a must-have!

**Comment by fr1zle** [comment]
@pikeas atom highlighting is available if you choose a fitting theme. Using "Atom One Dark" it looks like this:

![image](https://user-images.githubusercontent.com/311019/31066626-7cbe870e-a74e-11e7-96c5-44ab799fa42c.png)

**Comment by fr1zle** [comment]
This will be added in the next release

![image](https://user-images.githubusercontent.com/311019/32270419-280b6ee2-bef6-11e7-988c-7e0921488ee1.png)
