### ISSUE TITLE
Autocomplete not working (hangs on "Loading...")

### ISSUE THREAD

**Issue by hbobenicio** [fr1zle/vscode-elixir#65]
Environment:

Visual Studio Code: 1.12.1
vscode-elixir: 0.4.1
OS: Kubuntu 16.04 LTS

Issue Description:

Autocompletion suddenly stopped working (since a few weeks ago, not sure when exactly).
When trying to autocomplete some Elixir code with CTRL+Space, the box "Loading..." pops up and doen't resolve in anything.

Developt Console gives the following error:
"[Extension Host] [vscode-elixir] server is busy / not ready                 extensionHost.ts:285"

![bug-vscode-elixir-intellisense](https://cloud.githubusercontent.com/assets/1121074/26022044/651d49e4-3770-11e7-9923-09fbf2a9b613.png)

**Comment by hbobenicio** [comment]
Just saw that is may be related to Issue #30 . It won't work Elixir Suggestions nor Word Suggestions.

Forgot to inform:
My Elixir Instalation:

$ elixir --version
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.2

It was installed with [asdf version manager](https://github.com/asdf-vm/asdf) and [asdf-elixir plugin](https://github.com/asdf-vm/asdf-elixir), which configures the $PATH variable on ~/.bashrc to point to elixir's installation path (which in my case is: ~/.asdf/shims

**Comment by fr1zle** [comment]
Hey, thanks for reporting, I am sorry to hear you are having this issue.

Did the issue appear once you started using asdf? Can you get me the output of `which elixir`?
Can you restart VSCode and let me know what is logged in the developer console right after the start?

Thank you!

**Comment by hbobenicio** [comment]
It's totally ok! =)
Thanks for the quick answer!

Nope, I have always had asdf from the beginning. I use it at work too and the autocompletion works there! 

```
$ which elixir
/home/hugo/.asdf/shims/elixir

which erl
/home/hugo/.asdf/shims/erl

$ ls  /home/hugo/.asdf/shims/
ct_run  dialyzer  elixir  elixirc  epmd  erl  erlc  escript  iex  mix  run_erl  to_erl  typer
```

Anymore info I could provide or test I could made, please, let me know.
Thanks!

**Comment by hbobenicio** [comment]
One curiosity: How does vscode-elixir builds the suggestion list? Does it parse my code and erlang/elixir code searching for symbols (or symbols files) from times to times? Is there a way to debug this process?

**Comment by jfh-crim** [comment]
I'm having the same issue on my computer at work, but my home computer is fine. I'm scratching my head to find the difference. On both, I installed the latest version of VS Code, and used brew to install Elixir.

The one difference I found is, for some reason, my default login shell is csh at work and bash at home. Not sure if it's supposed to make any difference. I change it to bash just in case, but I still have the same problem.

**Comment by fr1zle** [comment]
Sorry, i have been a bit busy this weekend.

Could you ( @hbobenicio  & @jfh-crim ) try to navigate to `~/.vscode/extensions/mjmcloug.vscode-elixir-0.4.1/out/src/elixirServer.js` and change line 8 from 
`        this.command = 'elixir';`
to:
`        this.command = 'your/elixir/bin/path/elixir';

And check for me if that changes anything?

**Comment by jfh-crim** [comment]
In fact, I rebooted my computer, which I hadn't done after changing my default login shell to bash, and now it works! So I do think it's somehow related. Or... there was some unrelated problem which got fixed rebooting my Mac.

Now:
>[Extension Host] [vscode-elixir] Initializing alchemist-server for environment "dev" (Elixir version 1.4.2)

**Comment by hbobenicio** [comment]
@fr1zle , sorry for the delay. These has been some busy days here...
Well.. changed that as described. Same error though.

**Comment by hbobenicio** [comment]
Actually, I was only checking the autocomplete use case.
I noticed that, when VSCode starts, I get this (with `this.command = '/home/hugo/.asdf/shims/elixir';`)

![image](https://cloud.githubusercontent.com/assets/1121074/26181501/e5cc4890-3b46-11e7-9621-3633a3bda815.png)


and this as default (with `this.command = 'elixir';`):
![image](https://cloud.githubusercontent.com/assets/1121074/26181546/56350c8e-3b47-11e7-8061-008c3dd074e5.png)

**Comment by hbobenicio** [comment]
I think I'm getting what it's happening...

Just added the following:

`
// elixirServer.js - ElixirServer() function
console.log('PATH: ' + process.env.PATH);
console.log('PWD: ' + process.env.PWD);
`

And I got this:
![image](https://cloud.githubusercontent.com/assets/1121074/26181812/7485994a-3b49-11e7-9a2c-4b480f8edafe.png)

As I configured my Elixir path on ~/.bashrc, it was not executed by VSCode startup. So PATH contains no info about Elixir nor Erlang installation paths.

Is there a configuration file or something that I could tell vscode-elixir the correct installation path for them?

**Comment by hbobenicio** [comment]
Got it working now... just after starting VSCode from terminal (which opens as a child process from bash, which loaded ~/.bashrc)!

I was opening VSCode by the shortcuts from my desktop. I don't know how it won't work from the desktop or lauchers (created by vscode .deb installations), but at least I can use the autocomplete now =).

Anyway, thanks for the help, @fr1zle .
I guess we can close the issue.
If I discover why vscode doesn't load ~/.bashrc if opened from shortcuts, I'm gonna write it here as a complementary tip.

**Comment by fr1zle** [comment]
Okay, maybe make sure that bash is your login - shell as well?

I am closing this for now as this issue seems to be specific to users environments.
