### ISSUE TITLE
Documentation Enhancement - Theme Info

### ISSUE THREAD

**Issue by thegaryroberts** [fr1zle/vscode-elixir#68]
Can you update the Readme with details of the VS Code theme being used in the syntax highlighting examples.

I've not been able to get matching highlighting with any theme I've tested and this would make it clear if it is a bug with the extension or a configuration issue on my machine. Thanks.

**Comment by fr1zle** [comment]
Sure! Will add this info soon. For now: I am using the 'Atom One Dark' Theme.

**Comment by thegaryroberts** [comment]
Great thanks, that explains how I couldn't get it working. Installed that 'Atom One Dark' theme and all syntax highlighting matches the examples now 👍 

FYI: When using the 'Dark+ (default dark)' theme, there is no special colouring for the following
- `do:`
- `:atom`
- `#{...}` (i.e. string interpolation delimiters, the inner characters are coloured correctly)

Some of these have been mentioned in other issues, and it appears this is due to limitations of that default theme. Just noting here for reference.
