### ISSUE TITLE
Wrong indentation `case` with multiline clauses

### ISSUE THREAD

**Issue by kaelumania** [fr1zle/vscode-elixir#71]
When having a `case` statement with multiline clauses, the indentation is wrong. I experienced similiar issues with `vim-elixir` (https://github.com/elixir-lang/vim-elixir), where most of the things got fixed. Maybe you could have a look at their implementation.

**Comment by fr1zle** [comment]
hey, can you add an example screenshot? i think i know what you mean but having it visualised would be nice.
Thank you!

**Comment by kaelumania** [comment]
I think as formatting is not part of this plugin, it's the wrong place to open an issue. sorry.
