### ISSUE TITLE
Tab completion keyword ordering in test suite

### ISSUE THREAD

**Issue by bcardarella** [fr1zle/vscode-elixir#72]
Not sure if this is being sorted by vscode and if the order can be changed, but in the test suite when you write:

```elixir
test "some test"
```

the tab completion menu will then show:

<img width="972" alt="screen shot 2017-07-07 at 7 03 14 am" src="https://user-images.githubusercontent.com/18524/27955515-2eec0cf4-62e3-11e7-9766-7684e25e20c2.png">

with `doctest` as the first keyword to use. This is a frustrating experience as you almost always want `do` here. (`doctest` isn't even valid here) and the avoid the wrong keyword being inserted you have to use the menu to select `do`.

Is there a way we can improve the completion keywords here or change the order?

**Comment by PotterDai** [comment]
Change vscode setting "editor.snippetSuggestions" to "top" will resolve the problem.

**Comment by bcardarella** [comment]
Confirm, seems to be the case. Thank you.
