### ISSUE TITLE
moduledoc support

### ISSUE THREAD

**Issue by Iulian7** [fr1zle/vscode-elixir#76]
Maybe I have misconfigured something but it doesn't seem like the plugin knows about `@moduledoc`. 

![screen shot 2017-07-21 at 13 35 01](https://user-images.githubusercontent.com/11798936/28461986-72f4b586-6e19-11e7-9605-08266c7ea335.png)

![screen shot 2017-07-21 at 13 35 47](https://user-images.githubusercontent.com/11798936/28462004-8651e1d0-6e19-11e7-963e-f77d12ab0f2b.png)

What is more, if I type everything manually it completes extra `"` making me having to always delete `"` on the first and last lines. This is very frustrating. 

![screen shot 2017-07-21 at 13 37 43](https://user-images.githubusercontent.com/11798936/28462073-e0e5ad8e-6e19-11e7-93d7-9b85f67f9a98.png)

![screen shot 2017-07-21 at 13 38 01](https://user-images.githubusercontent.com/11798936/28462075-e47ccbda-6e19-11e7-9e6d-e242cfe0f160.png)

![screen shot 2017-07-21 at 13 38 15](https://user-images.githubusercontent.com/11798936/28462082-e94e0c00-6e19-11e7-9783-087937b6c798.png)

For me this is the most annoying bug with this otherwise excellent extension because it is actually counterproductive (typing it out plain text is better than having to delete, move cursor, delete again).

**Comment by fr1zle** [comment]
This should propably be a snippet.

**Comment by fr1zle** [comment]
This has been added as a snippet
