### ISSUE TITLE
Inconsistent syntax highlighting for one line functions

### ISSUE THREAD

**Issue by Iulian7** [fr1zle/vscode-elixir#78]
I don't know if this is a bug or if there is a reason for this it just seems inconsistent. `do` has a different colour than in the full form: 

![screen shot 2017-07-21 at 13 48 45](https://user-images.githubusercontent.com/11798936/28462479-c4f6b864-6e1b-11e7-9d52-98781431c0fb.png)

**Comment by mattbaker** [comment]
This seems reasonable to me since `do` is serving as a [keyword](https://elixir-lang.org/getting-started/case-cond-and-if.html#doend-blocks) in the latter example, but that's just my 0.02 as a passerby :)

**Comment by fr1zle** [comment]
I have to agree with @mattbaker on this. The context is different.
