### ISSUE TITLE
Go to Definition not working on Windows

### ISSUE THREAD

**Issue by patrickpichler** [fr1zle/vscode-elixir#79]
When you try to use the "Go to Definition"-Feature on Windows, you will get an error reading e.g. "Unable to open 'd': File not found (\d).".

This problem is caused by the way the path is splitted in the file "elixirSenseDefinitionProvider.ts" on line 33. On Windows you will get a path like `D:\Elixir\Example\file1.ex:1` which will lead to a wrong initializiation of the `filePath`-Variable, which is causing the error.

**Comment by fr1zle** [comment]
@patrickpichler can you install the latest update (0.5.1) and confirm that this has been fixed?

**Comment by patrickpichler** [comment]
@fr1zle its working now! Thank you!
