### ISSUE TITLE
Is there a way to get in the autocomplete first the snippets?

### ISSUE THREAD

**Issue by mrkaspa** [fr1zle/vscode-elixir#88]
When I'm going to declare a function I type def but when I hit the one with the red cube it doesn't put the snippet, the snippet one is the one at the bottom

![screen shot 2017-08-29 at 10 39 05 am](https://user-images.githubusercontent.com/764271/29829965-6e629046-8ca6-11e7-9d7f-07cf69c675ab.png)

**Comment by fr1zle** [comment]
You can only change this for every suggestion by setting "editor.snippetSuggestions" to top in your settings.
