### ISSUE TITLE
Support multiple folders in workspace

### ISSUE THREAD

**Issue by sadesyllas** [fr1zle/vscode-elixir#89]
First of all congratulations for your extension, it's great! 😃 👍 

With regard to multiple folder support I see in the source that you are using `vscode.workspace.rootPath` which has been recently deprecated in favor of the new workspace related API.

Are you planning to support this change soon?

Would you be interested in a pull request where we start a client/server per workspace folder?

Then, e.g., the autocomplete providers could do all their processing and resolve their promise with the results only if the document is in fact in the `projectPath`, for which the client/server have been started.

Plus, when the workspace folders change, servers can be started/stopped according to which folders have been added/removed to/from the workspace.

I haven't had time to go through all the code of the extension but it seems that we could easily change it to support the multiple folders in a workspace.

**Comment by mat-mcloughlin** [comment]
It a common situation where you'd work on multiple elixir apps within the same workspace?

Would it be better just have a menu to select which folder you want to work from?

**Comment by sadesyllas** [comment]
For me, it's quite common I believe.

For example, I am currently working on a group of apps where one depends on the other but I don't want them under an umbrella project.

They have to be in different repos.

So, in this case it's a huge time saver to be able to go from project to project in the same window.

Yesterday I implemented what I have written above, after forking this repo, and it seems to work fine for me (installed locally via the vsix package).

**Comment by sadesyllas** [comment]
@mat-mcloughlin I just realized that didn't really answer your question above.

I think that having a menu and unloading/loading a server for the deselected/selected folder would be too time consuming when going from folder to folder.

On the other hand, having 100 folders in the same workspace would perhaps make my proposal unsusable.

In any case, I think that without misuse of the workspaces feature, having a server ready for each folder is a reasonable solution.

And just in case someone wants to opt out from the automatic spawning of the servers (1/folder), the menu could also be easily implemented thus spawning nothing until the user selects a folder.

This way, everyone's happy. 😃

**Comment by sadesyllas** [comment]
In the forked repo I have implemented the following, which I am currently using:

1. On activation and if `useElixirSense` is `true`:
   1. If `autoSpawnElixirSenseServers` is `true` then we have the behavior described above: 1 server/folder where the folder must have a `mix.exs` as a direct child (since in a workspace elixir projects can reside alongside non-elixir projects)
   2. If `autoSpawnElixirSenseServers` is `false` then nothing happens except for when we only have a single folder in the workspace (as a shortcut) where a server is spawned automatically
   3. A command is registered (`extension.selectElixirSenseWorkspaceFolder`) which shows a menu with the currently added workspace folders
   4. When selecting a workspace folder via the menu
      1. If `autoSpawnElixirSenseServers` is `true` a message is shown, notifying the user that no action is required and nothing happens
      2. If `autoSpawnElixirSenseServers` is `false` then the user picks a workspace folder, the previously started server is stopped and a new one is started for the selected folder
2. On deactivation and if `useElixirSense` is `true`:
   1. Every spawned server is stopped and its subscriptions disposed of

What are your thoughts on this implementation?

**Comment by mat-mcloughlin** [comment]
I'm wondering where the PR is :P

Sounds good to me but need to hear from @fr1zle on this too

**Comment by fr1zle** [comment]
I honestly haven't looked much into the details of the vscode - extension API changes. Can you provide a link for the workspace related changes?

**Comment by sadesyllas** [comment]
@mat-mcloughlin, I have to agree. Having the PR could prove beneficial. 😃 

I just made the PR here: #91.

@fr1zle, the API and the deprecation warning of `rootPath` are here: https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace.
