### ISSUE TITLE
Autocomplete Not Working

### ISSUE THREAD

**Issue by akcorp2003** [fr1zle/vscode-elixir#94]
Here are my specs:

MacOS Sierra 10.12.6
VS Code 1.16

```
Erlang/OTP 20 [erts-9.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.1
```

```
$ which elixir
/usr/local/bin/elixir
```

I can't get autocomplete to work on a .esx file. I've already tried reinstalling the extension. No error seems to be popping up in the Developer Console in VS Code.

<img width="563" alt="screen shot 2017-09-11 at 2 55 48 pm" src="https://user-images.githubusercontent.com/12402936/30298733-5fa051be-9701-11e7-9ff5-8436c8969dce.png">

But I am getting the code snippets so the extension installed properly:

<img width="644" alt="screen shot 2017-09-11 at 2 56 03 pm" src="https://user-images.githubusercontent.com/12402936/30298755-6d2681be-9701-11e7-9a01-fdda456e0635.png">

**Comment by fr1zle** [comment]
Hey, currently autocomplete only works in mix projects. Do you have a mix project open or are you just testing in a exs file?

**Comment by akcorp2003** [comment]
Ah. I just had a plain exs file open.

**Comment by fr1zle** [comment]
Did you try a mix project? Did it work?

**Comment by akcorp2003** [comment]
Looks like it's working on a mix project! I'm getting the proper autocompletes that I expect.

<img width="758" alt="screen shot 2017-09-12 at 10 53 50 am" src="https://user-images.githubusercontent.com/12402936/30340851-b7cb383e-97a8-11e7-8a46-018f681174c4.png">
