### ISSUE TITLE
Autocomplete on function ignores aliased modules

### ISSUE THREAD

**Issue by fr1zle** [fr1zle/vscode-elixir#97]
Given that you have aliased a module:

```elixir
alias Exircd.Channel
```
Whenn typing
```elixir
Channel.nam
```
and selecting the autocomplete for `Exircd.Channel.name` 

the InsertText for the completion is the full module name and therefore the aliased modules function shows up as

```elixir
Exircd.Channel.name
```

**Comment by fr1zle** [comment]
@untra this seems to have been introduced by #90 

Changing
```typescript
if (type === 'function' && origin) {
  return `${origin}.${name}`;
}
```
to 
```typescript
if (type === 'function' && origin) {
  return `${name}`;
}
```
Will lead to only `name` being inserted.
Is there a way to fix this in the extension, or should this be fixed in elixir-sense?

**Comment by untra** [comment]
hmm... we need a way to tell if the origin has been previously aliased. elixir-sense doesn't tell us that. And just inserting the name will give an incorrect insertion if the origin wasn't previously aliased.

I don't have the bandwidth to look at this at the moment, however.
