### ISSUE TITLE
Integrate elixir 1.6 code formatter

### ISSUE THREAD

**Issue by fr1zle** [fr1zle/vscode-elixir#99]
see:

http://devonestes.herokuapp.com/everything-you-need-to-know-about-elixirs-new-formatter

if `editor.formatOnSave` is set to true, we should run the formatter on save.

Maybe we can even provide a formatting extension point as described here:

https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices

**Comment by securingsincity** [comment]
I can take this one.

**Comment by RumataEstor** [comment]
It's already being done here: #102

**Comment by dylan-chong** [comment]
whats going on with this? i notice that the current formatOnSave does not respect the rules from mix format
